### ISSUE TITLE
About Eedi dataset

### ISSUE THREAD

**Issue by ZhijieXiong** [oezyurty/KCQRL#1]
Thank you for your outstanding work. I have a question regarding the Eedi dataset. I wasn't able to find an application link for the dataset on [Eedi's website](https://eedi.com/). Could you please clarify which version of the dataset you used—was it from NeurIPS 2020, NeurIPS 2022, or possibly a new dataset? Thank you!

**Comment by oezyurty** [comment]
Thank you for your interest in our work! 

It's not any of these NeurIPS datasets you mentioned, that's why I didn't refer any of them in our paper either. It's a new dataset we acquired via our research partnership. 

As you would appreciate, I cannot speak on behalf of Eedi team. However, I believe you can reach out to their research them (and their chief data scientist) to get the dataset. After you acquired the data, you can pre-process it via our scripts. 

Of note, I didnt inspect NeurIPS 2020 or 2022 datasets in detail. Perhaps, one can do the reverse engineering to check if the fields in our pre-processing script are matching any of these datasets. If you can find a match, I think you can use these datasets within our framework as well. (Of course, the final performance will be different as the distributions won't be the same.)

Hope my message clarifies your question!
